apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xwms-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: wms-core
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: web-admin
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

configMapGenerator:
  - name: wms-env
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev
      - LOG_LEVEL=DEBUG
