apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xwms-staging

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: wms-core
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/metadata/labels/tier
        value: blue

configMapGenerator:
  - name: wms-env
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=staging
      - LOG_LEVEL=INFO
